<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <EnableDefaultItems>false</EnableDefaultItems>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <AssemblyName>BIMaestro</AssemblyName>
    <RootNamespace>BIMaestro</RootNamespace>
    <PlatformTarget>x64</PlatformTarget>
    <LangVersion>9.0</LangVersion>
    <Nullable>annotations</Nullable>
    <RevitVersion Condition="'$(RevitVersion)' == ''">2025</RevitVersion>
    <DefineConstants>$(DefineConstants);REVIT2025_OR_GREATER</DefineConstants>
    <RevitInstallDir>C:\Program Files\Autodesk\Revit $(RevitVersion)</RevitInstallDir>
    <DynamoForRevitDir>$(RevitInstallDir)\AddIns\DynamoForRevit</DynamoForRevitDir>
    <OutputPath>bin\Revit$(RevitVersion)\$(Configuration)\</OutputPath>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <EnableUnsafeBinaryFormatterSerialization>false</EnableUnsafeBinaryFormatterSerialization>
  </PropertyGroup>
  <Import Project="BIMaestro.SharedItems.props" />
  <ItemGroup>
    <PackageReference Remove="System.IO;System.IO.FileSystem.Primitives;System.Net.Http;System.Runtime;System.Runtime.InteropServices.RuntimeInformation;System.Security.Cryptography.Algorithms;System.Security.Cryptography.Encoding;System.Security.Cryptography.Primitives;System.Security.Cryptography.X509Certificates;System.Text.RegularExpressions" />
    <PackageReference Update="System.Security.Cryptography.Pkcs" Version="8.0.1" />
    <Reference Remove="System*;Microsoft.Build.Engine;Microsoft.VisualBasic;Microsoft.CSharp;PresentationCore;PresentationFramework;WindowsBase;WindowsFormsIntegration" />
    <COMReference Remove="@(COMReference)" />
    <Reference Include="Microsoft.Office.Interop.Excel">
      <HintPath>C:\Windows\assembly\GAC_MSIL\Microsoft.Office.Interop.Excel\15.0.0.0__71e9bce111e9429c\Microsoft.Office.Interop.Excel.dll</HintPath>
      <EmbedInteropTypes>true</EmbedInteropTypes>
    </Reference>
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="8.0.0" />
    <PackageReference Include="System.Security.Cryptography.ProtectedData" Version="8.0.0" />
  </ItemGroup>
</Project>
