<Project>
  <PropertyGroup Condition="'$(MSBuildProjectName)' == 'BIMaestro.Revit2025'">
    <RevitVersion Condition="'$(RevitVersion)' == ''">2025</RevitVersion>
    <BaseIntermediateOutputPath>obj\Revit$(RevitVersion)\</BaseIntermediateOutputPath>
    <MSBuildProjectExtensionsPath>$(BaseIntermediateOutputPath)</MSBuildProjectExtensionsPath>
  </PropertyGroup>
</Project>
