<Project ToolsVersion="15.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <Import Project="$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props" />
  <PropertyGroup>
    <Configuration Condition=" '$(Configuration)' == '' ">Debug</Configuration>
    <Platform Condition=" '$(Platform)' == '' ">AnyCPU</Platform>
    <OutputType>Exe</OutputType>
    <AssemblyName>BIMaestro.ViewDeck.Tests</AssemblyName>
    <TargetFrameworkVersion>v4.8</TargetFrameworkVersion>
    <LangVersion>9.0</LangVersion>
    <OutputPath>bin\$(Configuration)\</OutputPath>
    <PlatformTarget>x64</PlatformTarget>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="System" />
    <Reference Include="System.Core" />
    <Reference Include="WindowsBase" />
    <Reference Include="PresentationCore" />
    <Reference Include="PresentationFramework" />
    <Reference Include="System.Xaml" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="Program.cs" />
    <Compile Include="..\BIMaestro\commands\vue en survol\ViewDeckChangeJournal.cs">
      <Link>ViewDeckChangeJournal.cs</Link>
    </Compile>
    <Compile Include="..\BIMaestro\commands\vue en survol\ViewDeckTabPresentation.cs">
      <Link>ViewDeckTabPresentation.cs</Link>
    </Compile>
    <Compile Include="..\BIMaestro\commands\vue en survol\ViewDeckHoverPreview.cs">
      <Link>ViewDeckHoverPreview.cs</Link>
    </Compile>
    <Compile Include="..\BIMaestro\commands\vue en survol\ViewDeckPreviewMemory.cs">
      <Link>ViewDeckPreviewMemory.cs</Link>
    </Compile>
    <Compile Include="..\BIMaestro\commands\vue en survol\ViewDeckTabDecorator.cs">
      <Link>ViewDeckTabDecorator.cs</Link>
    </Compile>
    <Compile Include="..\BIMaestro\commands\vue en survol\ViewDeckTabIdentity.cs">
      <Link>ViewDeckTabIdentity.cs</Link>
    </Compile>
  </ItemGroup>
  <Import Project="$(MSBuildToolsPath)\Microsoft.CSharp.targets" />
</Project>
